version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///banking.db
      - JWT_SECRET_KEY=your-secret-key-change-this
      - FLASK_ENV=development
    volumes:
      - ../data:/app/data

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000