global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert-rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  # AWS ECS Metrics
  - job_name: 'aws-ecs'
    static_configs:
      - targets: ['aws-metrics-exporter:9106']
    scrape_interval: 60s